---
title: "Pengenalan Data Spasial"
author: "Elardian Putera Ramadhan (G1401231042)"
date: "2025-08-20"
output: html_document
---

```{r}
library(sf)
library(sp)
library(mapview)
library(spData)
library(ggplot2)
library(spatstat)
```


```{r}
d <- st_read(system.file("shape/nc.shp", package = "sf"),
             quiet = TRUE)
mapview(d, zcol = "SID74")
mapview(d, zcol = "SID74")
```

```{r}
plot(clmfires, use.marks = FALSE, pch = ".")
```

```{r}
plot(hamster)
```

```{r}
data(meuse)
meuse <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992) # 28992 adalah EPSG resmi belanda
mapview(meuse, zcol = "lead",  map.types = "CartoDB.Voyager")
```

```{r}
mapview(properties, zcol = "prpsqm")
```

```{r}
data(meuse)
meuse <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992)
coord <- st_coordinates(meuse)
```

```{r}
plot(meuse[1], main = "points")
```

```{r}
line <- SpatialLines(list(Lines(list(Line(coord)), "line1")))
plot(line, main = "lines")
```

```{r}
data("meuse.riv")
meuse.lst <- list(Polygons(list(Polygon(meuse.riv)), "meuse.riv"))
meuse.pol <- SpatialPolygons(meuse.lst)

plot(meuse.pol, col = "grey", main ="polygons")
```

```{r}
pathraster <- system.file("ex/elev.tif", package = "terra")
r <- terra::rast(pathraster)
r
```

```{r}
plot(r)
```

```{r}
st_crs("EPSG:4326")$Name
```

```{r}
st_crs("EPSG:4326")$epsg
```

```{r}
library(sf)
pathshp <- system.file("shape/nc.shp", package = "sf")
map <- st_read(pathshp, quiet = TRUE)

st_crs(map) # cek CRS untuk tau sistem koordinat apa yang dipakai data aslinya
```

```{r}
# Transform CRS
map2 <- st_transform(map, crs = "EPSG:4326")
st_crs(map2)
```

```{r}
library(terra)
pathraster <- system.file("ex/elev.tif", package = "terra")
r <- rast(pathraster)
crs(r) # cek CRS dari raster untuk tau sistem koordinat aslinya.
```

```{r}
# Transform CRS
r2 <- terra::project(r, "EPSG:2169")
crs(r2)
```

```{r}
pathshp <- system.file("shape/nc.shp", package = "sf")
```

```{r}
nc <- st_read(pathshp, quiet = TRUE)
class(nc)
```

```{r}
st_crs(nc)
```

```{r}
head(nc, 5)
```

```{r}
plot(nc)
```

```{r}
plot(nc[1]) #plot salah satu atribut
```

```{r}
veg<-st_read(dsn="C:/Users/Putera Ramadhan/Downloads/cape_peninsula-20250820T032740Z-1-001/cape_peninsula/veg", layer="Vegetation_Indigenous")
```

```{r}
st_crs(veg)
```

```{r}
class(veg)
```

```{r}
head(veg)
```

```{r}
plot(veg)
```

```{r}
plot(veg[3])
```

```{r}
ggplot() +
  geom_sf(data = veg, aes(fill = "National_"))
```

